myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    AboutMeView,
    AvatarUpdateView,
    UsersListView,
    RegisterView,
    MyLogoutView,
    HelloView,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view
)

app_name = "myauth"

urlpatterns = [
    path("login/",
         LoginView.as_view(template_name="myauth/login.html",
                           redirect_authenticated_user=True),
         name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("avatar-update/<int:pk>/", AvatarUpdateView.as_view(), name="avatar-update"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = [
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path("blog/", include("blogapp.urls"), name="blog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
]

urlpatterns += i18n_patterns(
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("shop/", include("shopapp.urls")),
    path("accounts/", include("myauth.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_directory_path(instance: "User", filename: str) -> str:
    return "users/avatars/user_{pk}/{filename}".format(
        pk=instance.user.pk,
        filename=filename
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=1000, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

myauth/forms.py
from django import forms
from .models import Profile


class UserAvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar"]

myauth/views.py
from random import random
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, ListView
from django.views.decorators.cache import cache_page
from django.utils.translation import gettext_lazy as _, ngettext
from .models import Profile, User
from .forms import UserAvatarForm


class HelloView(View):
    welcome_message = _("welcome hello world!")
    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one products",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>",
            f"\n<h2>{products_line}</h2>"
        )


class UsersListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy("myauth:login")
    template_name = "myauth/users-list.html"
    queryset = User.objects.all()
    context_object_name = "users"


class AboutMeView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("myauth:login")
    template_name = "myauth/about-me.html"
    context_object_name = "user"
    model = User

    def get_object(self, queryset=None):
        print(self.request.GET.get("id"))
        if self.request.GET.get("id"):
            return User.objects.get(id=self.request.GET.get("id"))
        else:
            return User.objects.get(id=self.request.user.id)




class AvatarUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = UserAvatarForm
    template_name = "myauth/avatar-update.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        print(form)
        return response

    def test_func(self):
        if self.request.user.is_staff:
            return True
        self.object = self.get_object()
        return self.object.user_id == self.request.user.id

    def get_success_url(self):
        return reverse("myauth:about-me")


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


# def login_view(request: HttpRequest) -> HttpResponse:
#     if request.method == "GET":
#         if request.user.is_authenticated:
#             return redirect("/shop/orders/")
#         return render(request, "myauth/login.html")
#
#     username = request.POST["username"]
#     password = request.POST["password"]
#
#     user = authenticate(request, username=username, password=password)
#     if user:
#         login(request, user)
#         return redirect("/shop/orders/")
#     return render(request, "myauth/login.html", {"error": "Invalid login credentials"})
#
#
# def logout_view(request: HttpRequest):
#     logout(request)
#     return redirect(reverse("myauth:login"))


# class MyLogoutView(LogoutView):
#     next_page = reverse_lazy("myauth:login")

# class MyLoginView(LoginView):
#     next_page = reverse_lazy("myauth:about-me")

class MyLogoutView(TemplateView):
    template_name = "myauth/logout.html"

    def post(self, request):
        logout(request)
        return redirect(reverse("myauth:login"))

def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("bar", "lcd", max_age=3600)
    return response


@cache_page(120)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("bar", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

myauth/templates/myauth/about-me.html
{% extends "myauth/base.html" %}
{% load cache %}

{% block title %}
    About Me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        {% cache 300 userinfo user.username %}
        <h2>User info: {{ user.username }}</h2>
        <h2>Details</h2>
        {% if user.profile.avatar %}
            <div>
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" width="200px" height="200px">
                {% if request.user.is_staff or user.id == request.user.id %}
                    <a href="{% url 'myauth:avatar-update' pk=user.profile.pk %}">Reset avatar</a>
                {% endif %}
            </div>
        {% else %}
            <div>No avatar</div>
            {% if request.user.is_staff or user.id == request.user.id %}
                <a href="{% url 'myauth:avatar-update' pk=user.profile.pk %}">Set avatar</a>
            {% endif %}
        {% endif %}
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        <div></div>
        {% endcache %}
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
    <div>
        <a href="{% url 'myauth:users-list' %}">See all users</a>
    </div>
{% endblock %}

myauth/templates/myauth/avatar-update.html
{% extends "myauth/base.html" %}

{% block title %}
    About Me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Details</h2>
        {% if user.profile.avatar %}
            <div>
                <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Reset avatar</button>
            </form>
        {% else %}
            <div>No avatar</div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Set avatar</button>
            </form>
        {% endif %}
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Body elements
    {% endblock %}
</body>
</html>

myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

myauth/templates/myauth/logout.html
{% extends "myauth/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>User registration</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

myauth/templates/myauth/users-list.html
{% extends "myauth/base.html" %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users list</h1>
    {% for user in object_list %}
        <a href="{% url 'myauth:about-me' %}?id={{user.id}}">More details</a>
        {% if user.profile.avatar %}
            <div>
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}" width="200px" height="200px">
            </div>
        {% else %}
            <div>No avatar</div>
        {% endif %}
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
    {% endfor %}
{% endblock %}