myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    AboutMeView,
    AvatarUpdateView,
    UsersListView,
    RegisterView,
    MyLogoutView,
    HelloView,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view
)

app_name = "myauth"

urlpatterns = [
    path("login/",
         LoginView.as_view(template_name="myauth/login.html",
                           redirect_authenticated_user=True),
         name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("avatar-update/<int:pk>/", AvatarUpdateView.as_view(), name="avatar-update"),
    path("users-list/", UsersListView.as_view(), name="users-list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = [
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path("blog/", include("blogapp.urls"), name="blog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
]

urlpatterns += i18n_patterns(
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("shop/", include("shopapp.urls")),
    path("accounts/", include("myauth.urls")),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter
from .views import (ShopIndex,
                    GroupsList,
                    LatestProductsFeed,
                    ProductViewSet,
                    ProductsListView,
                    ProductDetailsView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ProductsDataExportView,
                    OrderViewSet,
                    OrdersListView,
                    OrderDetailsView,
                    OrderCreateView,
                    OrderUpdateView,
                    OrderDeleteView,
                    OrdersExportView,
                    UserOrdersListView,
                    UserOrdersExportView)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)
routers.register("users", UserOrdersExportView, "orders")

urlpatterns = [
    #path("", cache_page(180)(ShopIndex.as_view()), name="index"),
    path("", ShopIndex.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsList.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archived", ProductDeleteView.as_view(), name="product_delete"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export", ProductsDataExportView.as_view(), name="products-export"),
    path("products/latest/feed/", LatestProductsFeed(), name="products-feed"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/export", OrdersExportView.as_view(), name="orders-export"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders")
]

shopapp/models.py
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.urls import reverse

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
    name = models.CharField(max_length=100, db_index=True)
    color = models.CharField(max_length=40, db_index=True)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=10000, max_digits=6, decimal_places=0)
    discount = models.PositiveSmallIntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name="products")
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})


    # @property
    # def description_short(self):
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self):
        return f"Product ({self.name!r}, color: {self.color})"

def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=25)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="orders")
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т. д.
"""
import logging
import json
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser
from django_filters.rest_framework import DjangoFilterBackend
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.core.cache import cache
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy as _, ngettext
from drf_spectacular.utils import extend_schema, OpenApiResponse
from .models import Product, Order, ProductImage
from .forms import ProductForm, OrderForm, GroupForm
from .serializers import ProductSerializer, OrderSerializer
from .common import save_csv_products
from django.contrib.auth.models import User, Group
from django.contrib.syndication.views import Feed
from timeit import default_timer
from csv import DictWriter


#log = logging.getLogger(__name__)


class LatestProductsFeed(Feed):
    title = "Products (latest)"
    description = "Updates on changes and addition products"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return Product.objects.filter(created_at__isnull=False).order_by("-created_at")[:5]

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:100]

    def item_link(self, item: Product):
        return item.get_absolute_url()


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        OrderingFilter
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived"
    ]
    ordering_fields = [
        "name",
        "price",
        "discount"
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @method_decorator(cache_page(120))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount"
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow({field: getattr(product, field) for field in fields})
        return response

    @action(methods=["post"], detail=False, parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding="UTF-8"
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter
    ]
    search_fields = ["delivery_address", "user"]
    filterset_fields = [
        "delivery_address",
        "promocode",
        "created_at",
        "user"
    ]
    ordering_fields = [
        "delivery_address",
        "user"
    ]


class ShopIndex(View):
    #@method_decorator(cache_page(120))
    def get(self, request):
        products = [
            {"name": "Samsung A03", "price": 8990, "color": "black", "qty": 5},
            {"name": "Samsung A13", "price": 15990, "color": "blue", "qty": 7},
            {"name": "Samsung A52", "price": 30990, "color": "red", "qty": 8},
            {"name": "Samsung A73", "price": 41990, "color": "blue", "qty": 2}
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": 5,
            "header": "Welcome to Samsung GALAXY store",
            "title": "Samsung GALAXY Store"
        }
        #log.debug("Products for shop index: %s", products)
        #log.info("Rendering shop index")
        print("shop index context", context)
        return render(request, "shopapp/shop-index.html", context=context)


class GroupsList(View):
    def get(self, request):
        context = {
            "title": "Groups list",
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related("permissions").all()
        }
        return render(request, "shopapp/groups-list.html", context=context)

    def post(self, request):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    #model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductsListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy("myauth:login")
    template_name = "shopapp/products-list.html"
    queryset = Product.objects.filter(archived=False)
    context_object_name = "products"


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    template_name = "shopapp/create-product.html"
    form_class = ProductForm
    model = Product
    #fields = "name", "color", "description", "price", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    #fields = "name", "color", "description", "price", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        self.object = self.get_object()

        has_edit_perm = self.request.user.has_perm("shopapp.change_product")
        created_by_current_user = self.object.created_by == self.request.user
        return has_edit_perm and created_by_current_user

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk}
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
        return JsonResponse({"products": products_data})


# class ProductsListView(TemplateView):
#     template_name = "shopapp/products-list.html"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["products"] = Product.objects.all()
#         return context


# def products_list(request):
#     context = {
#         "title": "Products list",
#         "products": Product.objects.all()
#     }
#     return render(request, "shopapp/products-list.html", context=context)


# def create_product(request):
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             return redirect(reverse("shopapp:products_list"))
#     else:
#         form = ProductForm()
#     context = {"form": form}
#     return render(request, "shopapp/create-product.html", context=context)


class OrdersListView(LoginRequiredMixin, ListView):

shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Body elements
    {% endblock %}
</body>
</html>

shopapp/templates/shopapp/create-order.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create an order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            >Back to orders
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/create-product.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block title %}
    {% translate 'CrP' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'CrP' %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% translate 'Create' %}</button>
        </form>
    </div>
    <div>
        {% url 'shopapp:products_list' as products_list_url %}
        {% blocktranslate %}
        <a href="{{ products_list_url }}">
            >Back to products list
        </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

shopapp/templates/shopapp/groups-list.html
{% extends "shopapp/base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h2>Not groups yet</h2>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>
                            {{ group.name }}
                        </div>
                        <ul>
                            {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

shopapp/templates/shopapp/order_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create an order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            >Back to orders
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/order_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    <div>
        {% if not object_list %}
            <h2>Not orders yet</h2>
        {% else %}
            <div>
                {% for order in object_list %}
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details № {{ order.pk }}</a>
                    </p>
                    <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode: {{ order.promocode }}</p>
                    <p>Delivery address: {{ order.delivery_address }}</p>
                    <div>
                        Product in order:
                        <ul>
                            {% for product in order.products.all %}
                            <li>{{ product.name }} for {{ product.price }} rub.</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            >Create a new order
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/order_update.html
{% extends "shopapp/base.html" %}

{% block title %}
    Update a product
{% endblock %}

{% block body %}
    <h1>Update current order № {{ object.pk }}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">
            >Back to order № {{ object.pk }}
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
            Import orders from CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

shopapp/templates/shopapp/product_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
    Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archived {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">
            >Back to product № {{ object.pk }}
        </a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create a product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            >Back to products list
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Update a product
{% endblock %}

{% block body %}
    <h1>Update product {{ product.name }}</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">
            >Back to product № {{ object.pk }}
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html" %}

{% load i18n %}

{% block title %}
    {% blocktranslate %}{{ title }}{% endblocktranslate %}
{% endblock %}

{% block body %}
    <h1>{% translate 'PTitle' %}:</h1>
    <div>
        {% if not products %}
            <h2>{% translate 'NoProducts' %}</h2>
        {% else %}
            <div>
                {% blocktranslate count products_count=products|length %}
                    There is only one product.
                    {% plural %}
                    There are {{ products_count }} products.
                {% endblocktranslate %}
            </div>
            <div>
                {% for product in products %}
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">
                        {% translate 'Name' context 'product name' %}: {{ product.name }}</a>
                    </p>
                    <p>{% translate 'Color' %}: {{ product.color }}</p>
                    <p>{% translate 'Price' %}: {{ product.price }}</p>
                    {% translate 'no discount' as no_discount %}
                    <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </div>

    {% if perms.shopapp.add_product %}
    {% url 'shopapp:product_create' as create_product_url %}
    <div>
        <a href="{{ create_product_url }}">
            >{% translate 'Create a new product' %}
        </a>
    </div>
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/shop-index.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        Time running: {{ time_running }}
    </div>
    <h1>{{ header }}</h1>

    <div>
        <h2>{{ products|length }} product{{ products|pluralize }} available for orders:</h2>
        <ul>
            {% for product in products|dictsort:"price" %}
            <li>{{ product.name }} for {{ product.price }} rub.
                {% if product.qty %}
                    available: {{ product.qty }}
                {% else %}
                    not available now
                {% endif %}
            </li>
            {% empty %}
            No products here
            {% endfor %}
        </ul>
    </div>

    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>

    <div>
        {% now "H:i" %}
    </div>

    {% cache 100 weekday %}
    <div>
        {% now "l" as current_weekday %}
        Today is {{ current_weekday }}
    </div>
    {% endcache %}

{% endblock %}

shopapp/templates/shopapp/user_orders.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block title %}
    User orders info
{% endblock %}

{% block body %}
    {% if order_list %}
    <h1>User {{ owner.username }} created these orders:</h1>
    <div>
        {% cache 600 orderinfo owner.username %}
        {% for order in order_list %}
        <h2>Order #{{ forloop.counter }}</h2>
        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"></a></p>
        <p>Delivery address: {{ order.delivery_address }}</p>
        <p>Promocode: {{ order.promocode }}</p>
        <p>Products in order:</p>
        <ul>
            {% for product in order.products.all %}
            <li>{{ product.name }} {{ product.price }}rub</li>
            {% endfor %}
        </ul>
        {% endfor %}
        {% endcache %}
    </div>
    {% else %}
        <h1>User {{ owner.username }} haven't created orders yet</h1>
    {% endif %}
{% endblock %}